##################################################################
## Packages / Gangen / Tnx to Cvoid for help                     ##
## @darkgeej - https://github.com/darkgeej/bett-has             ##
##################################################################
homeassistant:
  customize:

    input_number.gang_vaeg_lamper:
      icon: mdi:lightbulb-on-outline
      friendly_name: Væglamper i gangen


###########
## Group ##
###########
group:

  Gang:
    control: hidden
    name: "Gangen"
    view: no
    entities:
      - input_number.gang_vaeg_lamper

  Ganglamp:
    control: hidden
    name: "Gangenlamper"
    view: no
    entities:
      - light.hojre
      - light.lance_venstre_g


###############
### Sliders ###
###############
input_number:
  gang_vaeg_lamper:
    name: gangvaeglamp
    initial: 254
    min: 0
    max: 254
    step: 1


################
## Automation ##
################
automation:

  - alias: Væglamper i gangen
    trigger:
      platform: state
      entity_id: input_number.gang_vaeg_lamper
    action:
      - service: light.turn_on
        data_template:
          entity_id: group.ganglamp
          brightness: "{{ trigger.to_state.state | int }}"

