##################################################################
## Packages / Stuen / Tnx to Cvoid for help         ##
## @darkgeej - https://github.com/darkgeej/Home-AssistantConfig ##
##################################################################
homeassistant:
  customize:

    input_number.stue_vindue_lamp:
      icon: mdi:lightbulb-on-outline
      friendly_name: Lampen i vinduet

    input_number.stue_vaeg_lamper:
      icon: mdi:lightbulb-on-outline
      friendly_name: Væglamper


###########
## Group ##
###########
group:

  Stue:
    control: hidden
    name: "Stuen"
    view: no
    entities:
      - input_number.stue_vaeg_lamper
      - input_number.stue_vindue_lamp
  
  Vaeglampe:
    control: hidden
    name: "Vaeglamper"
    view: no
    entities:
      - light.stuevenstre
      - light.stuehojre


### Sliders ###

input_number:
  stue_vaeg_lamper:
    name: stuenvaeglamp
    initial: 254
    min: 0
    max: 254
    step: 1

  stue_vindue_lamp:
    name: stuenvindueslampen  
    initial: 254
    min: 0
    max: 254
    step: 1


automation:

  - alias: Stuen vaeglamper
    trigger:
      platform: state
      entity_id: input_number.stue_vaeg_lamper
    action:
      - service: light.turn_on
        # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
        data_template:
          entity_id: group.vaeglampe
          brightness: "{{ trigger.to_state.state | int }}"

  - alias: Stuen vindueslampen
    trigger:
      platform: state
      entity_id: input_number.stue_vindue_lamp
    action:
      - service: light.turn_on
        # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
        data_template:
          entity_id: light.vindue_lampe
          brightness: "{{ trigger.to_state.state | int }}"
